# Generated by Django 5.2.8 on 2026-04-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_is_settlement_expense_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('home', 'Home'), ('trip', 'Trip'), ('couple', 'Couple'), ('personal', 'Personal'), ('business', 'Business'), ('office', 'Office'), ('sports', 'Sports'), ('others', 'Others')], default='personal', max_length=20),
        ),
    ]
