# Generated by Django 5.2.8 on 2026-04-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_split_type_expenseshare_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g., example@upi', max_length=50, null=True),
        ),
    ]
