# Generated by Django 5.2.8 on 2026-04-18 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expense_is_deleted_group_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload bill/receipt (PDF, JPG, PNG, etc.)', upload_to='bills/%Y/%m/%d/')),
                ('file_name', models.CharField(editable=False, max_length=255)),
                ('file_size', models.BigIntegerField(default=0, editable=False)),
                ('file_type', models.CharField(choices=[('bill', 'Bill/Receipt'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('proof', 'Payment Proof'), ('other', 'Other')], default='bill', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Optional description (e.g., "Electricity bill for March")', max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as primary/main bill')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all group members')),
                ('download_count', models.IntegerField(default=0, help_text='Track how many times downloaded')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='expenses.expense')),
                ('last_downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloaded_bills', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
                'indexes': [models.Index(fields=['expense', '-uploaded_at'], name='expenses_bi_expense_90d3e9_idx'), models.Index(fields=['uploaded_by', '-uploaded_at'], name='expenses_bi_uploade_4dbdba_idx')],
            },
        ),
    ]
